import { test, expect } from "@playwright/test";

test("EAA chat streams once, survives reload, and exposes runtime controls", async ({ page, request }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByText("Connected", { exact: true })).toBeVisible();
  const input = page.locator(".eaa-input-panel textarea");
  await input.fill("hello browser");
  await input.press("Enter");
  await expect(page.getByText("Demo reply: hello browser", { exact: true })).toHaveCount(1);
  await page.reload();
  await expect(page.getByText("Demo reply: hello browser", { exact: true })).toHaveCount(1);
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  await expect(page.getByRole("button", { name: "Run workflow", exact: true })).toBeDisabled();
  await page.getByRole("combobox", { name: "Workflow", exact: true }).selectOption("toy");
  await expect(page.getByRole("textbox", { name: "Workflow task" })).toHaveValue("");
  await expect(page.getByRole("button", { name: "Launch subagent", exact: true })).toBeDisabled();
  await page.getByRole("textbox", { name: "Subagent task" }).fill("   ");
  await expect(page.getByRole("button", { name: "Launch subagent", exact: true })).toBeDisabled();
  await page.getByRole("textbox", { name: "Workflow task" }).fill("Three example measurements");
  await page.getByRole("button", { name: "Run workflow", exact: true }).click();
  await expect.poll(async () => (await (await request.get("/api/state")).json()).conversations.some((c: any) => c.kind === "workflow" && c.messages.some((m: any) => m.role === "assistant")), { timeout: 60000 }).toBeTruthy();
  await expect.poll(async () => (await (await request.get("/api/workflows")).json()).runs.some((r: any) => r.status === "completed"), { timeout: 60000 }).toBeTruthy();
  await page.getByRole("button", { name: "Refresh runs", exact: true }).click();
  await expect(page.getByRole("button", { name: "Resume workflow", exact: true })).toBeVisible({ timeout: 60000 });
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await page.getByRole("button", { name: "Main Agent", exact: true }).click();
  await expect(page.getByText("Images (0)", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  await page.getByRole("textbox", { name: "Subagent task" }).fill("Say Reviewer finished");
  await expect(page.getByRole("button", { name: "Launch subagent", exact: true })).toBeDisabled();
  await page.getByRole("combobox", { name: "Subagent", exact: true }).selectOption("reviewer");
  await expect(page.getByRole("textbox", { name: "Workflow task" })).toHaveValue("Three example measurements");
  await page.getByRole("button", { name: "Launch subagent", exact: true }).click();
  await expect.poll(async () => (await (await request.get("/api/state")).json()).conversations.some((c: any) => c.kind === "subagent" && c.messages.length), { timeout: 60000 }).toBeTruthy();
  await expect(page.getByRole("button", { name: "Open terminal", exact: true })).toHaveCount(0);
  expect((await request.post("/api/terminals", { data: {} })).status()).toBe(201);
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await expect(page.getByRole("textbox", { name: "Terminal input" })).toBeVisible();
  await page.getByRole("textbox", { name: "Terminal input" }).fill("printf browser-terminal-ok");
  await page.getByRole("textbox", { name: "Terminal input" }).press("Enter");
  await expect(page.locator(".eaa-terminal-output")).toContainText("browser-terminal-ok", { timeout: 15000 });
  await page.getByRole("button", { name: "Close terminal", exact: true }).click();
  expect(errors).toEqual([]);
});

test("pending approval survives reconnect and plan controls block launch", async ({ page, request }) => {
  await expect.poll(async () => {
    const state = await (await request.get("/api/state")).json();
    return state.status === "waiting_for_input" && state.tool_execution_queue.length === 0;
  }).toBeTruthy();
  await page.goto("/");
  await page.getByRole("button", { name: "Main Agent", exact: true }).click();
  await page.locator(".eaa-input-panel textarea").fill("request approval");
  await page.locator(".eaa-input-panel textarea").press("Enter");
  await expect(page.getByRole("button", { name: "Yes", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Yes", exact: true })).toHaveCount(1);
  await page.getByRole("button", { name: "No", exact: true }).click();
  await expect(page.locator(".eaa-message-tool").filter({ hasText: "Denied" })).toBeVisible();
  await expect.poll(async () => (await (await request.get("/api/state")).json()).status).toBe("waiting_for_input");
  await page.getByText("Plan mode", { exact: true }).click();
  await expect(page.getByRole("switch", { name: "Plan mode" })).toBeChecked();
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  await expect(page.getByRole("button", { name: "Run workflow", exact: true })).toBeDisabled();
  expect((await request.post("/api/terminals", { data: {} })).status()).toBe(409);
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await page.getByText("Plan mode", { exact: true }).click();
  await expect(page.getByRole("switch", { name: "Plan mode" })).not.toBeChecked();
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  await page.getByRole("combobox", { name: "Workflow", exact: true }).selectOption("toy");
  await expect(page.getByRole("button", { name: "Run workflow", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await page.getByLabel("Upload image").setInputFiles({ name: "toy.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a/lkAAAAASUVORK5CYII=", "base64") });
  await expect(page.locator(".eaa-input-panel textarea")).toHaveValue(/<img /);
  await page.locator(".eaa-input-panel textarea").press("Enter");
  await expect(page.getByText("Image received by the local fixture.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tools", exact: true }).click();
  await expect(page.getByRole("button", { name: "Reconnect toy" }).first()).toBeVisible();
});


test("sessions panel floats, resizes, and dismisses outside without shifting the layout", async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 });
  await page.goto("/");
  const panel = page.getByRole("complementary", { name: "Sessions and tools", exact: true });
  const workflow = page.getByRole("combobox", { name: "Workflow", exact: true });
  const before = await page.locator(".eaa-workspace").boundingBox();
  await expect(panel).toBeHidden();
  const toggle = page.getByRole("button", { name: "Expand sessions and tools" });
  await expect(page.getByRole("complementary", { name: "Primary navigation" }).getByRole("button", { name: "Expand sessions and tools" })).toBeVisible();
  await toggle.click();
  await expect(workflow).toBeVisible();
  await workflow.selectOption("toy");
  expect(await page.locator(".eaa-workspace").boundingBox()).toEqual(before);
  const box = (await panel.boundingBox())!;
  await page.mouse.move(box.x + box.width - 3, box.y + box.height - 3);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width + 97, box.y + box.height + 57, { steps: 10 });
  await page.mouse.up();
  const resized = (await panel.boundingBox())!;
  expect(resized.width).toBeGreaterThan(box.width + 50);
  expect(resized.height).toBeGreaterThan(box.height + 30);
  expect(await page.locator(".eaa-workspace").boundingBox()).toEqual(before);
  await page.screenshot({ path: "/tmp/eaa-floating-panel.png" });
  await page.getByRole("button", { name: "Chat", exact: true }).click();
  await expect(panel).toBeHidden();
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await toggle.click();
  await expect(workflow).toHaveValue("toy");
  expect((await panel.boundingBox())!.width).toEqual(resized.width);
  await page.keyboard.press("Escape");
  await expect(panel).toBeHidden();
  await toggle.click();
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await expect(panel).toBeHidden();
  await page.setViewportSize({ width: 390, height: 844 });
  await toggle.click();
  await expect(workflow).toBeVisible();
  const mobile = (await panel.boundingBox())!;
  expect(mobile.x + mobile.width).toBeLessThanOrEqual(390);
  expect(mobile.y + mobile.height).toBeLessThanOrEqual(844);
  await page.screenshot({ path: "/tmp/eaa-floating-panel-mobile.png" });
  await page.mouse.click(385, 830);
  await expect(panel).toBeHidden();
});


test("subagent section lists agents and handles an empty catalog", async ({ page }) => {
  let agents = [{ name: "inspector", description: "Inspect data" }, { name: "writer", description: "Write a report" }];
  await page.route("**/api/agents", route => route.fulfill({ json: { agents } }));
  await page.goto("/");
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  const section = page.getByRole("region", { name: "Subagents", exact: true });
  const select = section.getByRole("combobox", { name: "Subagent", exact: true });
  await expect(select.locator("option")).toHaveText(["Select an agent", "inspector", "writer"]);
  await select.selectOption("writer");
  await expect(section.getByText("Write a report", { exact: true })).toBeVisible();
  const launch = section.getByRole("button", { name: "Launch subagent" });
  await expect(launch).toBeDisabled();
  await section.getByRole("textbox", { name: "Subagent task" }).fill("  ");
  await expect(launch).toBeDisabled();
  await section.getByRole("textbox", { name: "Subagent task" }).fill("Summarize the findings");
  await page.route("**/api/subagents", async route => {
    if (route.request().method() !== "POST") return route.continue();
    expect(route.request().postDataJSON()).toEqual({ agent: "writer", task: "Summarize the findings" });
    await route.fulfill({ json: {} });
  });
  const sent = page.waitForRequest(request => request.url().endsWith("/api/subagents") && request.method() === "POST");
  await launch.click();
  await sent;
  agents = [];
  await page.getByRole("button", { name: "Collapse sessions and tools" }).click();
  await page.getByRole("button", { name: "Expand sessions and tools" }).click();
  await expect(select.locator("option")).toHaveText(["No agents available"]);
  await expect(select).toHaveValue("");
  await expect(launch).toBeDisabled();
});
